In [1]:
import numpy as np

Creating Numpy Array

In [8]:
# np.array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#3D
np.array([[[[1,2],[3,4]],[[5,6],[7,8]]]])

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [16]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [20]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
#with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#np.random
np.random.random((3,4))

array([[0.98086847, 0.76027198, 0.67023004, 0.14275494],
       [0.91484844, 0.80783441, 0.82806757, 0.11132064],
       [0.91184521, 0.20459767, 0.87133123, 0.00421282]])

In [40]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [42]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes